services:
  - type: web
    name: ph-diabetes-predictor
    runtime: python
    region: singapore  # Closest to the Philippines for faster access
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements-prod.txt
    startCommand: gunicorn app.app:app --workers 2 --threads 4 --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: PYTHONUNBUFFERED
        value: true